# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 7764536cca8af063cee3230bdd375a83b59823a1b6171b2f9f3f56e0726f3f782fce620095bfb042fd508ec156eeebc84917c42ad89b96019c9b58aaf660df5d

test:
  domain_name: example.com 
  secret_key_base: ca9ccd96308ad158ba96064a8dd07e3d94ebf1588e3d07e574d367ed2a20ed845d39134260063ac25ffdf2d63a226dcfee5f4c023a2e2a8c99cb7bf9e4cfbfc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
